print("Welcome to Mad Libs!")
adj1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
adv1 = input("Enter an adverb: ")
adj2 = input("Enter another adjective: ")
noun2 = input("Enter another noun: ")
noun3 = input("Enter a plural noun: ")
verb2 = input("Enter another verb: ")
adv2 = input("Enter another adverb: ")
noun4 = input("Enter one more noun: ")

print("Here's your story:")
print("The " + adj1 + " " + noun1 + " " + verb1 + " " + adv1 + " down the street, " + adj2 + " " + noun2 + " and " + noun3 + " " + verb2 + " " + adv2 + ". At the end of the road, there was a " + noun4 + ".")
